# Generated by Django 5.0 on 2023-12-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
