# Generated by Django 5.0 on 2024-01-02 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0002_carmodel_car_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
