# Generated by Django 5.0 on 2023-12-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodel',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
