# Generated by Django 5.0 on 2023-12-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_details', '0002_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='user',
            new_name='author',
        ),
    ]
